# This is a basic workflow to help you get started with Actions

name: Simple Task "simple-task-test"

on:
  push:
    branches:
    tags:

jobs:
  simple-task-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo 'success!'
