name: Wait using check-regexp
on:
  push:
    tags:
      - 'test-using-regexp/v*' # e.g. test-using-regexp/v1_2_3
jobs:
  wait-for-check-regexp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Wait on tests
        uses: ./
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10 # seconds
          running-workflow-name: wait-for-check-regexp
          check-regexp: .?-task

      - name: Success
        run: echo 'success!'
