name: Wait using check-regexp
on:
  workflow_dispatch:
  push:

jobs:
  simple-task:
    runs-on: ubuntu-latest
    steps:
      - name: Simple task
        run: echo 'done'

  wait-for-check-regexp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Wait on tests
        uses: ./
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10 # seconds
          running-workflow-name: wait-for-check-regexp
          check-regexp: .?-task

      - name: Success
        run: echo 'success!'
